// Authoritative list of Avi Controller REST object types, extracted from a live
// controller's /swagger/ index (window.objectTypes). The REST path for each is
// simply the lowercased name (e.g. VirtualService -> /api/virtualservice) --
// verified against several irregularly-capitalized names (SSLKeyAndCertificate,
// HTTPPolicySet, IpAddrGroup, PKIProfile, ...).
export const ALL_OBJECT_TYPES: string[] = [
  "ActionGroupConfig",
  "ALBServicesConfig",
  "ALBServicesFileDownload",
  "ALBServicesFileUpload",
  "ALBServicesJob",
  "Alert",
  "AlertConfig",
  "AlertEmailConfig",
  "AlertObjectList",
  "AlertScriptConfig",
  "AlertSyslogConfig",
  "AnalyticsProfile",
  "Anomaly",
  "ApiRateLimitProfile",
  "Application",
  "ApplicationInsightsPolicy",
  "ApplicationPersistenceProfile",
  "ApplicationProfile",
  "AuthMappingProfile",
  "AuthProfile",
  "AutoScaleLaunchConfig",
  "AvailabilityZone",
  "Backup",
  "BackupConfiguration",
  "BotConfigConsolidator",
  "BotDetectionPolicy",
  "BotIPReputationTypeMapping",
  "BotMapping",
  "CertificateManagementProfile",
  "CertJwtStore",
  "Cloud",
  "CloudConnectorUser",
  "CloudInventory",
  "CloudProperties",
  "CloudRuntime",
  "ClusterCloudDetails",
  "ControllerPortalRegistration",
  "ControllerProperties",
  "ControllerSite",
  "CSRFPolicy",
  "CustomIpamDnsProfile",
  "DebugController",
  "DebugServiceEngine",
  "DebugVirtualService",
  "DnsPolicy",
  "DynamicDnsRecord",
  "ErrorPageBody",
  "ErrorPageProfile",
  "FileObject",
  "GeoDB",
  "Gslb",
  "GslbCRMRuntime",
  "GslbGeoDbProfile",
  "GslbHSMRuntime",
  "GslbInventory",
  "GslbService",
  "GslbServiceInventory",
  "GslbSMRuntime",
  "HardwareSecurityModuleGroup",
  "HealthMonitor",
  "HealthScore",
  "HTTPPolicySet",
  "IcapProfile",
  "Image",
  "InventoryFaultConfig",
  "IpAddrGroup",
  "IpamDnsProviderProfile",
  "IPReputationDB",
  "JobEntry",
  "JWTServerProfile",
  "L4PolicySet",
  "LabelGroup",
  "LicenseLedgerDetails",
  "LicenseStatus",
  "LocalWorkerFdsVersion",
  "LogControllerMapping",
  "MemoryBalancerRequest",
  "Metrics",
  "MicroService",
  "MicroServiceGroup",
  "NatPolicy",
  "Network",
  "NetworkInventory",
  "NetworkProfile",
  "NetworkRuntime",
  "NetworkSecurityPolicy",
  "NetworkService",
  "NsxtSegmentRuntime",
  "PKIProfile",
  "Pool",
  "PoolGroup",
  "PoolGroupDeploymentPolicy",
  "PoolGroupInventory",
  "PoolInventory",
  "PositiveSecurityPolicy",
  "PriorityLabels",
  "ProtocolParser",
  "RateLimitConfiguration",
  "Report",
  "ReportProfile",
  "RetentionPolicy",
  "Role",
  "Scheduler",
  "SCPoolServerStateInfo",
  "SCVsStateInfo",
  "SecureChannelAvailableLocalIPs",
  "SecureChannelMapping",
  "SecureChannelToken",
  "SecurityManagerData",
  "SecurityPolicy",
  "SeProperties",
  "ServerAutoScalePolicy",
  "ServiceAuthProfile",
  "ServiceEngine",
  "ServiceEngineGroup",
  "ServiceEngineGroupInventory",
  "ServiceEngineInventory",
  "SiteVersion",
  "SnmpTrapProfile",
  "SSLKeyAndCertificate",
  "SSLProfile",
  "SSOPolicy",
  "SspInstance",
  "StatediffOperation",
  "StatediffSnapshot",
  "StringGroup",
  "SystemConfiguration",
  "SystemLimits",
  "SystemReport",
  "TaskJournal",
  "TechSupport",
  "TechSupportMessage",
  "TechSupportProfile",
  "Tenant",
  "TenantBinding",
  "TenantSystemConfiguration",
  "TestSeDatastoreLevel1",
  "TestSeDatastoreLevel2",
  "TestSeDatastoreLevel3",
  "TrafficCloneProfile",
  "TrustedHostProfile",
  "UpgradeProfile",
  "UpgradeStatusInfo",
  "UpgradeStatusSummary",
  "User",
  "UserAccountProfile",
  "UserActivity",
  "VCenterServer",
  "VIDCInfo",
  "VIMgrClusterRuntime",
  "VIMgrHostRuntime",
  "VIMgrNWRuntime",
  "VIMgrSEVMRuntime",
  "VIMgrVMRuntime",
  "VIPGNameInfo",
  "VirtualService",
  "VrfContext",
  "VSDataScriptSet",
  "VsGs",
  "VsInventory",
  "VsVip",
  "VsvipInventory",
  "WafApplicationSignatureProvider",
  "WafCRS",
  "WafPolicy",
  "WafPolicyPSMGroup",
  "WafPolicyPSMGroupInventory",
  "WafProfile",
  "WebappUT",
  "Webhook"
];

/**
 * A curated highlight of the object types most agents will need, grouped by
 * functional area. This is a subset of ALL_OBJECT_TYPES for quick discovery --
 * every other type in ALL_OBJECT_TYPES is equally usable with avi_list/avi_get/etc,
 * it's just less commonly needed.
 */
export const COMMON_OBJECT_TYPES: { category: string; types: { name: string; description: string }[] }[] = [
  {
    category: "Load Balancing",
    types: [
      { name: "VirtualService", description: "A load-balanced service: listens on a VIP/port and forwards to a pool" },
      { name: "Pool", description: "A set of backend servers with health checks and load-balancing algorithm" },
      { name: "PoolGroup", description: "Weighted/prioritized group of pools behind a single virtual service" },
      { name: "VsVip", description: "Virtual IP address configuration shared/attached to virtual services" },
      { name: "ApplicationProfile", description: "L4/L7 protocol behavior profile (HTTP, DNS, TCP, ...) attached to a VS" },
      { name: "NetworkProfile", description: "Transport-layer (TCP/UDP) profile attached to a virtual service" },
      { name: "ApplicationPersistenceProfile", description: "Client persistence/stickiness configuration for a pool" },
    ],
  },
  {
    category: "Health & Monitoring",
    types: [
      { name: "HealthMonitor", description: "Active health check definition (HTTP/HTTPS/TCP/UDP/DNS/...) used by pools" },
      { name: "HealthScore", description: "Computed health score history for an object" },
      { name: "Anomaly", description: "Detected anomalies for monitored objects" },
      { name: "Alert", description: "Fired alert instances" },
      { name: "AlertConfig", description: "Alert rule definitions (what triggers an alert)" },
      { name: "Metrics", description: "Time-series analytics; use avi_get_analytics instead of avi_list for this" },
    ],
  },
  {
    category: "Security",
    types: [
      { name: "SSLKeyAndCertificate", description: "TLS certificate + private key objects" },
      { name: "SSLProfile", description: "TLS protocol/cipher policy" },
      { name: "PKIProfile", description: "CA bundle used to validate certificates" },
      { name: "WafPolicy", description: "Web Application Firewall policy" },
      { name: "WafProfile", description: "WAF engine tuning profile" },
      { name: "NetworkSecurityPolicy", description: "L3/L4 allow/deny rules for a virtual service" },
      { name: "HTTPPolicySet", description: "L7 HTTP request/response switching, redirect and header rules" },
      { name: "BotDetectionPolicy", description: "Bot management policy" },
      { name: "AuthProfile", description: "Authentication backend (SAML/LDAP/OAuth) definition" },
    ],
  },
  {
    category: "Networking",
    types: [
      { name: "Network", description: "L2/L3 network/subnet definitions known to Avi" },
      { name: "VrfContext", description: "Virtual routing and forwarding context" },
      { name: "IpAddrGroup", description: "Named group of IP addresses/ranges, reusable in policies" },
      { name: "IpamDnsProviderProfile", description: "IPAM/DNS provider integration used for VS IP/FQDN allocation" },
    ],
  },
  {
    category: "Cloud Integration",
    types: [
      { name: "Cloud", description: "Infrastructure connector (vCenter, AWS, Azure, NSX-T, no-orchestrator, ...)" },
      { name: "ServiceEngine", description: "A deployed data-plane instance (the actual load-balancing engine)" },
      { name: "ServiceEngineGroup", description: "Placement/sizing/HA policy for a group of service engines" },
      { name: "VCenterServer", description: "Registered vCenter server used by a vCenter cloud" },
    ],
  },
  {
    category: "Global Load Balancing (GSLB)",
    types: [
      { name: "Gslb", description: "GSLB federation configuration (sites, DNS)" },
      { name: "GslbService", description: "A globally load-balanced DNS service across sites" },
      { name: "GeoDB", description: "Geolocation database mapping for GSLB/DNS decisions" },
    ],
  },
  {
    category: "Administration",
    types: [
      { name: "Tenant", description: "Multi-tenancy boundary" },
      { name: "SystemConfiguration", description: "Controller-wide system settings" },
      { name: "BackupConfiguration", description: "Scheduled configuration backup settings" },
      { name: "User", description: "Local user accounts" },
      { name: "Role", description: "RBAC role definitions" },
    ],
  },
];
